from .views import *
from django.urls import path

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/', UserProfileListAPIView.as_view(), name='user_list'),
    path('user/<int:pk>/', UserProfileDetailAPIView.as_view(), name='user_detail'),
    path('topic/', TopicListAPIView.as_view(), name='topic_list'),
    path('topic/<int:pk>/', TopicDetailAPIView.as_view(), name='topic_detail'),
    path('task/', TaskListAPIView.as_view(), name='task_list'),
    path('task/<int:pk>/', TaskDetailAPIView.as_view(), name='task_detail'),
    path('submission/', SubmissionListAPIView.as_view(), name='submission_list'),
    path('submission/<int:pk>/', SubmissionDetailAPIView.as_view(), name='submission_detail'),
    path('dailyplan/', DailyPlanListAPIView.as_view(), name='dailyplan_list'),
    path('dailyplan/<int:pk>/', DailyPlanDetailAPIView.as_view(), name='dailyplan_detail'),
    path('livelesson/', LiveLessonListAPIView.as_view(), name='livelesson_list'),
    path('livelesson/<int:pk>/', LiveLessonDetailAPIView.as_view(), name='livelesson_detail'),
    path('testsession/', TestSessionListAPIView.as_view(), name='testsession_list'),
    path('testsession/<int:pk>/', TestSessionDetailAPIView.as_view(), name='testsession_detail'),
    path('testparticipant/', TestParticipantListAPIView.as_view(), name='testparticipant_list'),
    path('testparticipant/<int:pk>/', TestParticipantDetailAPIView.as_view(), name='testparticipant_detail'),
    path('question/', QuestionListAPIView.as_view(), name='question_list'),
    path('question/<int:pk>/', QuestionDetailAPIView.as_view(), name='question_detail'),
    path('answeroption/', AnswerOptionListAPIView.as_view(), name='answeroption_list'),
    path('answeroption/<int:pk>/', AnswerOptionDetailAPIView.as_view(), name='answeroption_detail'),
    path('answer/', AnswerListAPIView.as_view(), name='answer_list'),
    path('answer/<int:pk>/', AnswerDetailAPIView.as_view(), name='answer_detail'),
    path('hackathonsession/', HackathonSessionListAPIView.as_view(), name='hackathonsession_list'),
    path('hackathonsession/<int:pk>/', HackathonSessionDetailAPIView.as_view(), name='hackathonsession_detail'),
    path('hackathonparticipant/', HackathonParticipantListAPIView.as_view(), name='hackathonparticipant_list'),
    path('hackathonparticipant/<int:pk>/', HackathonParticipantDetailAPIView.as_view(), name='hackathonparticipant_detail'),
    path('hackathonsubmission/', HackathonSubmissionListAPIView.as_view(), name='hackathonsubmission_list'),
    path('hackathonsubmission/<int:pk>/', HackathonSubmissionDetailAPIView.as_view(), name='hackathonsubmission_detail'),
]